### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by amacneil** [foxglove/rosbag2-web#2]
Readme doesn't have any examples

**Comment by defunctzombie** [comment]
@esthersweon ping on this

**Comment by esthersweon** [comment]
Spoke with @jhurliman: "don't think these projects have any usage outside of studio... we don't want anyone to use them if possible, since they promote a file format we're actively working to kill off... say this is the (web/node.js) implementation of reading ROS 2 sqlite files, it's used in Studio for support of this legacy file format, and this format has been superseded by MCAP which you can read about here"

Based on this feedback, will revise README to do the following:

- Clarify the purpose of repo / clean up empty or dead sections
- Mention usage in Foxglove Studio
- Point people towards MCAP

**Comment by jediofgever** [comment]
> we don't want anyone to use them if possible, since they promote a file format we're actively working to kill off..

Too bad, but are there any alternatives? 

> Point people towards MCAP

Thank you!, could you point me to MCAP please

**Comment by amacneil** [comment]
https://mcap.dev/ 😄 

PS: The "kill off" comment above was referring to killing Foxglove support for db3. I don't think we actually pulled the trigger on that, but it's become much less relevant now that MCAP is available.
